---
title: "Analyzing trends of organ donor enrollment in New York state"
output: github_document
---

```{r setup and data import, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 300, out.width = "75%")

library(tidyverse)
library(lme4)
library(modelr)
library(kableExtra)
#using data cleaned in api_pull.rmd file

theme_set(theme_bw())

organ_sp <- read_csv("data/organ_spline.csv") %>% 
  filter(!(county %in% c("TOTAL NYS", "Cattauragus", "St Lawrence"))) %>% 
  mutate(opo = as_factor(opo), 
         opo = fct_relevel(opo, 
                           "New York Organ Donor Network", 
                           "Center for Donation and Transplant in New York", 
                           "UNYTS", 
                           "Finger Lakes Donor Recovery Network"))
```

|Name            | Uni       |
|----------------|-----------|
|Shuliang Deng   | sd3258    |
|Nick Williams   | ntw2117   |
|Sijia Yue       | sy2824    |
|Jack Yan        | xy2395    |
|Alina Levine    | al3851    |

[Click here for data](https://www.dropbox.com/sh/grlugs9hrksvkqr/AAAwILSg5UyMrW1CD7dWmHPNa?dl=0)

## Motivation

## Initial questions

## Data 

## Exploratory analyses

## Formal analyses

Formal analyses of the effect of major policy changes were conducted using mixed-effects linear models with a random intercept; counties were treated as the clustering variable. The outcome was analyzed was the proportion of eligible adults registered with one of four organ donor organizations. Four successive models were created: a model only analyzing a linear effect of time; a model including a term for a spline corresponding with a 2012 policy INSERT WHAT THIS POLICY WAS; a model including a term for a spline corresponding with a 2016 policy INSERT WHAT THIS POLICY WAS; a model including a term for a spline corresponding with a 2017 policy that lowered the age from eligible enrollees from 18 to 16 years old; and a model that included all splines. All models were adjusted for the specific organization used in each county; models were compared using likelihood ratio tests. 



## Discussion
